# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:41
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mediastore.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0002_auto_20170410_2253'),
        ('calendar', '0002_auto_20170410_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gallery',
            field=mediastore.fields.related.MultipleMediaField(blank=True, help_text=None, null=True, related_name='event_gallery', to='mediastore.Media'),
        ),
        migrations.AddField(
            model_name='event',
            name='main_image',
            field=mediastore.fields.related.MediaField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_main_image', to='mediastore.Media'),
        ),
        migrations.AddField(
            model_name='trips',
            name='gallery',
            field=mediastore.fields.related.MultipleMediaField(blank=True, help_text=None, null=True, related_name='trips_gallery', to='mediastore.Media'),
        ),
        migrations.AddField(
            model_name='trips',
            name='main_image',
            field=mediastore.fields.related.MediaField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trips_main_image', to='mediastore.Media'),
        ),
    ]
