# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 21:47
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0003_auto_20170410_2341'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventid', models.IntegerField(verbose_name='Event ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('club_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Club name')),
                ('club_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Club location')),
                ('from_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location From Name')),
                ('from_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='From location')),
                ('from_description', models.TextField(blank=True, null=True, verbose_name='From description')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From Date')),
                ('from_time', models.TimeField(blank=True, null=True, verbose_name='From Time')),
                ('to_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location To Name')),
                ('to_location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='To location')),
                ('to_description', models.TextField(blank=True, null=True, verbose_name='To description')),
                ('to_date', models.DateField(blank=True, null=True, verbose_name='To Date')),
                ('to_time', models.TimeField(blank=True, null=True, verbose_name='To Time')),
                ('river_closure', models.NullBooleanField(default=None, verbose_name='River Closure')),
                ('link', models.CharField(blank=True, max_length=255, null=True, verbose_name='Link')),
                ('group_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Type')),
                ('district_name_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='District name one')),
                ('district_description_one', models.CharField(blank=True, max_length=255, null=True, verbose_name='District description one')),
                ('district_name_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='District name two')),
                ('district_description_two', models.CharField(blank=True, max_length=255, null=True, verbose_name='District description two')),
                ('district_name_three', models.CharField(blank=True, max_length=255, null=True, verbose_name='District name three')),
                ('district_description_three', models.CharField(blank=True, max_length=255, null=True, verbose_name='District description three')),
                ('status_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status name')),
                ('status_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Status description')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('calendar', models.ManyToManyField(blank=True, null=True, to='calendar.Calendar')),
            ],
            options={
                'verbose_name_plural': 'PLA Events',
                'verbose_name': 'PLA Event',
                'ordering': ['eventid'],
            },
        ),
        migrations.AlterModelOptions(
            name='extrafields',
            options={'ordering': ['sort_value'], 'verbose_name': 'Extra Field', 'verbose_name_plural': 'Extra Fields'},
        ),
    ]
