# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 20:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0004_auto_20170411_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='TideData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='tides/%Y/')),
                ('inputted', models.BooleanField(default=False, verbose_name='Inputed data')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created'],
                'verbose_name': 'Tide Upload',
            },
        ),
    ]
