# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 23:25
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0006_tidedata_converted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='calendar',
            managers=[
                ('data', django.db.models.manager.Manager()),
            ],
        ),
    ]
