# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-23 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0007_auto_20170523_2325'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='calendar',
            managers=[
            ],
        ),
    ]
