# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0010_auto_20170525_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='weathertypes',
            name='icon',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Icon'),
        ),
    ]
