# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 09:33
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0011_weathertypes_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tidedata',
            name='converted',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(blank=True, null=True), size=None), blank=True, default=[], null=True, size=None),
        ),
    ]
