# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 00:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0013_windy'),
    ]

    operations = [
        migrations.AddField(
            model_name='windy',
            name='celsius',
            field=models.FloatField(blank=True, null=True, verbose_name='celsius'),
        ),
        migrations.AddField(
            model_name='windy',
            name='direction',
            field=models.FloatField(blank=True, null=True, verbose_name='Direction'),
        ),
        migrations.AddField(
            model_name='windy',
            name='speed',
            field=models.FloatField(blank=True, null=True, verbose_name='Speed'),
        ),
        migrations.AlterField(
            model_name='windy',
            name='day',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calendar.Calendar'),
        ),
        migrations.AlterField(
            model_name='windy',
            name='time',
            field=models.TimeField(blank=True, null=True, verbose_name='Time'),
        ),
    ]
