# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-25 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0014_auto_20171025_0009'),
    ]

    operations = [
        migrations.AddField(
            model_name='windy',
            name='water_celsius',
            field=models.FloatField(blank=True, null=True, verbose_name='water celsius'),
        ),
    ]
