# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar', '0016_auto_20171030_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='tidedata',
            name='year',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Year'),
        ),
    ]
