# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 15:52
from __future__ import unicode_literals

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('first_name', 'username'), unique=True),
        ),
    ]
