# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-31 00:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['postdate', 'sort_value'], 'permissions': (('can_publish', 'Can publish this item'),), 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
