# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-21 23:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0002_auto_20170831_0034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-postdate', '-sort_value'], 'permissions': (('can_publish', 'Can publish this item'),), 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
