# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:10
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mediastore.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0002_auto_20170410_2253'),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery',
            field=mediastore.fields.related.MultipleMediaField(blank=True, help_text=None, null=True, related_name='article_gallery', to='mediastore.Media'),
        ),
        migrations.AddField(
            model_name='article',
            name='main_image',
            field=mediastore.fields.related.MediaField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_main_image', to='mediastore.Media'),
        ),
    ]
