# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-21 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255, verbose_name='Question')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Answer')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('question',), unique=True)),
                ('sort_value', models.IntegerField(default=0, verbose_name='Sort Value')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['-sort_value'],
                'verbose_name_plural': 'FAQ',
            },
        ),
    ]
