# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 22:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_pageimages'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='homepage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pageimages',
            managers=[
            ],
        ),
    ]
