# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-18 21:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiry', '0003_auto_20170618_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newslettersignup',
            old_name='_name',
            new_name='name',
        ),
    ]
