# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 23:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mediastore.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0002_auto_20170410_2253'),
        ('clubsessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='location',
            field=mediastore.fields.related.MediaField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session_map', to='mediastore.Media'),
        ),
    ]
