# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 13:42


import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0002_auto_20170410_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='end',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Middle or End'),
        ),
        migrations.AlterField(
            model_name='map',
            name='path',
            field=django.contrib.gis.db.models.fields.LineStringField(blank=True, null=True, srid=4326, verbose_name='Path'),
        ),
        migrations.AlterField(
            model_name='map',
            name='start',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='Start'),
        ),
    ]
