# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 19:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0003_auto_20170524_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='end',
        ),
        migrations.RemoveField(
            model_name='map',
            name='end_name',
        ),
        migrations.RemoveField(
            model_name='map',
            name='start',
        ),
        migrations.RemoveField(
            model_name='map',
            name='start_name',
        ),
    ]
