# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-28 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'ordering': ['sort_value', 'created'], 'verbose_name': 'About', 'verbose_name_plural': 'Abouts'},
        ),
        migrations.AddField(
            model_name='about',
            name='sort_value',
            field=models.IntegerField(default=0, verbose_name='Sort Value'),
        ),
    ]
