# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-23 21:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import mediastore.fields.related


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mediastore', '0004_auto_20170525_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('title',), unique=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('list_description', models.CharField(blank=True, max_length=255, null=True, verbose_name='List Description')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('sort_value', models.IntegerField(default=0, verbose_name='Sort Value')),
                ('gallery', mediastore.fields.related.MultipleMediaField(blank=True, help_text=None, null=True, related_name='gallery_gallery', to='mediastore.Media')),
                ('main_image', mediastore.fields.related.MediaField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery_main_image', to='mediastore.Media')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['-sort_value'],
                'verbose_name': 'Gallery',
            },
        ),
    ]
