# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_public', models.BooleanField(default=False, verbose_name='Is Public')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Is Featured')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, overwrite=True, populate_from=('title',), unique=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True)),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True)),
                ('tagline', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tag line')),
                ('description', models.TextField(verbose_name='Description')),
                ('from_date', models.DateField(blank=True, null=True, verbose_name='From')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End')),
                ('cost', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cost')),
                ('sort_value', models.IntegerField(default=0, verbose_name='Sort Value')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'ordering': ['from_date', 'sort_value'],
            },
        ),
    ]
