# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-19 20:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mediastore.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('mediastore', '0004_auto_20170525_1932'),
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='download',
            field=mediastore.fields.related.MediaField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='membership_download', to='mediastore.Media'),
        ),
    ]
